### ISSUE TITLE
Pipeline cannot be copied due to permissions of aind-smartspim-classification capsule

### ISSUE THREAD

**Issue by galenlynch** [AllenNeuralDynamics/aind-smartspim-pipeline#1]
After copying the aind-smartspim-pipeline (v 2.0) pipeline, I am unable to run it because the [aind-smartspim-classification](https://github.com/AllenNeuralDynamics/aind-smartspim-classification) capsule is not public.

![image](https://github.com/user-attachments/assets/82b27d3f-6c5c-44f6-9be7-0e7010454a8f)

**Comment by camilolaiton** [comment]
Hi @galenlynch, this has been resolved in Code Ocean.
