### ISSUE TITLE
Incorrect Institution in data_description

### ISSUE THREAD

**Issue by miketaormina** [AllenNeuralDynamics/aind-smartspim-pipeline#4]
Recent data sets seem to always be labeled as AIND, despite the original processing_manifest indicating AIBS for some data sets.

One example can be found in`s3://aind-open-data/SmartSPIM_758723_2024-11-05_16-31-59/`, which has a conflict between the `processing_manifest` institution and the `data_description` institution.

This might not be in this repository, as I think this file is created on prem during an aind-data-trasnsfer job, but wherever the manifest should be ingested to create the data description, there must be a bug.

**Comment by camilolaiton** [comment]
Hi @miketaormina, thanks for reporting this. I am checking up with @jtyoung84 since this is happening previous to getting the data to our pipeline with our airflow service.

**Comment by miketaormina** [comment]
I will also note that other information in data_description does appear to be accurate (Investigators, for example, do seem to come from processing_manifest.json)

**Comment by miketaormina** [comment]
Closing with AllenNeuralDynamics/aind-smartspim-operator-utils#108
